app: serverless-chadchapters
service: serverless-chadchapters
frameworkVersion: '3'

provider:
  name: aws
  apiGateway:
      apiKeys:
      - name: apiKey
        value: ${env:MY_API_KEY}
  runtime: nodejs16.x
  timeout: 900 

functions:
  bot-get-last-videos:
    handler: src/bot-get-last-videos.handler
    events:
      - http:
          path: /bot/getlastvideos
          method: post
          private: true

  bot-comment-videos:
    handler: src/bot-comment-videos.handler
    events:
      - http:
          path: /bot/commentvideos
          method: post
          private: true          	

  bot-comment-video-cron:
    handler: src/bot-comment-video-cron.cron
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 hour)

useDotenv: true

    
plugins:
  # - serverless-plugin-typescript
  # - serverless-esbuild
  - serverless-offline

